// log-viewer-web/src/app/features/workflows/components/definition-condition.component.ts
import { Component, input, computed } from '@angular/core';
import {
  WorkflowConditionDef, DeviceStateConditionDef, TimeConditionDef,
  SceneActiveConditionDef, BlockResultConditionDef,
  LogicAndConditionDef, LogicOrConditionDef, LogicNotConditionDef,
} from '../../../core/models/workflow-definition.model';
import { formatComparisonOperator, formatTimeConditionMode } from '../../../core/utils/workflow-definition-utils';
import { IconComponent } from '../../../shared/components/icon.component';

@Component({
  selector: 'app-definition-condition',
  standalone: true,
  imports: [IconComponent, DefinitionConditionComponent],
  template: `
    <div class="condition-node">
      <div class="condition-row">
        @for (i of depthRange(); track i) {
          <div class="connector-line"></div>
        }

        @if (isLogic()) {
          <span class="logic-badge">{{ logicLabel() }}</span>
        } @else {
          <span class="condition-icon">
            <app-icon [name]="conditionIcon()" [size]="14" />
          </span>
        }

        <div class="condition-info">
          <span class="condition-name">{{ displayName() }}</span>
          @if (detailText()) {
            <span class="condition-detail">{{ detailText() }}</span>
          }
        </div>
      </div>

      @if (childConditions().length > 0) {
        @for (child of childConditions(); track $index) {
          <app-definition-condition [condition]="child" [depth]="depth() + 1" />
        }
      }
    </div>
  `,
  styles: [`
    .condition-node {
      font-size: var(--font-size-sm);
    }
    .condition-row {
      display: flex;
      align-items: center;
      gap: 6px;
      padding: 6px 0;
    }
    .connector-line {
      width: 2px;
      min-height: 24px;
      align-self: stretch;
      opacity: 0.3;
      border-radius: 1px;
      flex-shrink: 0;
      margin-left: 6px;
      background-color: var(--tint-secondary);
    }
    .condition-icon {
      display: flex;
      align-items: center;
      flex-shrink: 0;
      color: var(--text-tertiary);
    }
    .logic-badge {
      font-size: var(--font-size-xs);
      font-weight: var(--font-weight-bold);
      padding: 1px 6px;
      border-radius: 4px;
      background: color-mix(in srgb, var(--tint-secondary) 15%, transparent);
      color: var(--tint-secondary);
      text-transform: uppercase;
      flex-shrink: 0;
    }
    .condition-info {
      flex: 1;
      min-width: 0;
      display: flex;
      flex-direction: column;
      gap: 2px;
    }
    .condition-name {
      font-weight: var(--font-weight-semibold);
      color: var(--text-primary);
    }
    .condition-detail {
      color: var(--text-secondary);
      line-height: 1.4;
    }
  `]
})
export class DefinitionConditionComponent {
  condition = input.required<WorkflowConditionDef>();
  depth = input(0);

  readonly depthRange = computed(() => Array.from({ length: this.depth() }, (_, i) => i));

  readonly isLogic = computed(() => {
    const t = this.condition().type;
    return t === 'and' || t === 'or' || t === 'not';
  });

  readonly logicLabel = computed(() => {
    const t = this.condition().type;
    if (t === 'and') return 'AND';
    if (t === 'or') return 'OR';
    if (t === 'not') return 'NOT';
    return '';
  });

  readonly conditionIcon = computed(() => {
    switch (this.condition().type) {
      case 'deviceState': return 'house';
      case 'timeCondition': return 'clock';
      case 'sceneActive': return 'play-circle-fill';
      case 'blockResult': return 'checkmark-circle-fill';
      default: return 'bolt-circle-fill';
    }
  });

  readonly displayName = computed(() => {
    const c = this.condition();
    switch (c.type) {
      case 'deviceState': {
        const d = c as DeviceStateConditionDef;
        return d.deviceName || d.deviceId;
      }
      case 'timeCondition': {
        const t = c as TimeConditionDef;
        return formatTimeConditionMode(t.mode, t.startTime, t.endTime);
      }
      case 'sceneActive': {
        const s = c as SceneActiveConditionDef;
        const name = s.sceneName || s.sceneId;
        return `${name} is ${s.isActive ? 'active' : 'inactive'}`;
      }
      case 'blockResult': {
        const b = c as BlockResultConditionDef;
        const scope = b.blockResultScope.scope === 'specific'
          ? `Block ${b.blockResultScope.blockId?.substring(0, 8) || '?'}`
          : b.blockResultScope.scope === 'all' ? 'All blocks' : 'Any block';
        return `${scope} is ${b.expectedStatus}`;
      }
      case 'and': return 'All of the following';
      case 'or': return 'Any of the following';
      case 'not': return 'None of the following';
      default: return (c as any).type;
    }
  });

  readonly detailText = computed(() => {
    const c = this.condition();
    switch (c.type) {
      case 'deviceState': {
        const d = c as DeviceStateConditionDef;
        const parts: string[] = [];
        if (d.roomName) parts.push(d.roomName);
        parts.push(`${d.characteristicType} ${formatComparisonOperator(d.comparison)}`);
        return parts.join(' · ');
      }
      default: return undefined;
    }
  });

  readonly childConditions = computed((): WorkflowConditionDef[] => {
    const c = this.condition();
    if (c.type === 'and') return (c as LogicAndConditionDef).conditions;
    if (c.type === 'or') return (c as LogicOrConditionDef).conditions;
    if (c.type === 'not') return [(c as LogicNotConditionDef).condition];
    return [];
  });
}

// log-viewer-web/src/features/workflows/DefinitionCondition.tsx
import { useState, useMemo } from 'react';
import { Icon } from '@/components/Icon';
import { useDeviceRegistry } from '@/contexts/DeviceRegistryContext';
import type {
  WorkflowConditionDef, DeviceStateConditionDef, TimeConditionDef,
  SceneActiveConditionDef, BlockResultConditionDef,
  LogicAndConditionDef, LogicOrConditionDef, LogicNotConditionDef,
} from '@/types/workflow-definition';
import { formatComparisonOperator, formatTimeConditionMode } from '@/utils/workflow-definition-utils';
import './tree-common.css';

const DEPTH_COLORS = [
  'var(--depth-0)',
  'var(--depth-1)',
  'var(--depth-2)',
  'var(--depth-3)',
  'var(--depth-4)',
];

interface DefinitionConditionProps {
  condition: WorkflowConditionDef;
  depth?: number;
}

function getChildConditions(condition: WorkflowConditionDef): WorkflowConditionDef[] {
  switch (condition.type) {
    case 'and': return (condition as LogicAndConditionDef).conditions;
    case 'or': return (condition as LogicOrConditionDef).conditions;
    case 'not': return [(condition as LogicNotConditionDef).condition];
    default: return [];
  }
}

function isLogicOperator(type: string): boolean {
  return type === 'and' || type === 'or' || type === 'not';
}

export function DefinitionCondition({ condition, depth = 0 }: DefinitionConditionProps) {
  const registry = useDeviceRegistry();
  const [collapsed, setCollapsed] = useState(false);

  const children = getChildConditions(condition);
  const hasChildren = children.length > 0;
  const depthRange = Array.from({ length: depth }, (_, i) => i);

  const displayName = useMemo(() => {
    switch (condition.type) {
      case 'deviceState': {
        const d = condition as DeviceStateConditionDef;
        return registry.lookupDevice(d.deviceId)?.name || d.deviceId;
      }
      case 'timeCondition': return 'Time Condition';
      case 'sceneActive': {
        const s = condition as SceneActiveConditionDef;
        const scene = registry.lookupScene(s.sceneId);
        return scene?.name || s.sceneId;
      }
      case 'blockResult': return 'Block Result';
      case 'and': return 'All conditions (AND)';
      case 'or': return 'Any condition (OR)';
      case 'not': return 'NOT';
      default: return (condition as WorkflowConditionDef).type;
    }
  }, [condition, registry]);

  const detailText = useMemo(() => {
    switch (condition.type) {
      case 'deviceState': {
        const d = condition as DeviceStateConditionDef;
        const device = registry.lookupDevice(d.deviceId);
        const char = registry.lookupCharacteristic(d.deviceId, d.characteristicId);
        const charLabel = char?.name || d.characteristicId;
        const parts: string[] = [];
        if (device?.room) parts.push(device.room);
        parts.push(`${charLabel} ${formatComparisonOperator(d.comparison)}`);
        return parts.join(' · ');
      }
      case 'timeCondition': {
        const t = condition as TimeConditionDef;
        return formatTimeConditionMode(t.mode, t.startTime, t.endTime);
      }
      case 'sceneActive': {
        const s = condition as SceneActiveConditionDef;
        return s.isActive ? 'Is active' : 'Is not active';
      }
      case 'blockResult': {
        const b = condition as BlockResultConditionDef;
        const scope = b.blockResultScope.scope === 'specific' ? `Block ${b.blockResultScope.blockId}` : 'Last block';
        return `${scope} is ${b.expectedStatus}`;
      }
      default: return undefined;
    }
  }, [condition, registry]);

  const conditionIcon = isLogicOperator(condition.type) ? null : 'checkmark-circle';

  return (
    <div className="tree-node">
      <div
        className={`tree-row ${hasChildren ? 'collapsible' : ''}`}
        onClick={() => hasChildren && setCollapsed(v => !v)}
      >
        {depthRange.map(i => (
          <div
            key={i}
            className="connector-line"
            style={{ backgroundColor: DEPTH_COLORS[i % DEPTH_COLORS.length] }}
          />
        ))}

        {hasChildren && (
          <span className={`tree-chevron ${collapsed ? 'collapsed' : ''}`}>
            <Icon name="chevron-down" size={12} />
          </span>
        )}

        {isLogicOperator(condition.type) ? (
          <span className="logic-badge">{condition.type.toUpperCase()}</span>
        ) : (
          <span className="tree-icon" style={{ color: 'var(--tint-main)' }}>
            <Icon name={conditionIcon!} size={16} />
          </span>
        )}

        <div className="tree-info">
          <span className="tree-name">{displayName}</span>
          {detailText && <span className="tree-detail">{detailText}</span>}
          {collapsed && hasChildren && (
            <span className="collapsed-hint">{children.length} nested</span>
          )}
        </div>
      </div>

      {!collapsed && children.map((sub, i) => (
        <DefinitionCondition key={i} condition={sub} depth={depth + 1} />
      ))}
    </div>
  );
}
